### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by lurch** [rhulme/picoROM_pio#2]
> This is a proof-of-concept based on the idea of picoROM to simulate an EEPROM chip simply but using just PIO and DMA to improve the performance. I have no immediate use for this project myself but it piqued my interest to see what kind of improvement could be achieved.

*Is* this faster? If it is, what kind of improvement was achieved? :slightly_smiling_face: 

> The code as presented here just has an address and data bus of 4 bits to make testing easier but these are defined in eeprom.pio and can be easily changed and will not affect the efficiency.

Looking at the code in `main.c`, it seems that the address bus can't be bigger than 16 bits, and the data bus can't be bigger than 8 bits?

Might be worth adding the answers to both of these questions to `README.md` ? I also have no need for this myself, I just thought it looked like an interesting application :grinning:

**Comment by rhulme** [comment]
> > This is a proof-of-concept based on the idea of picoROM to simulate an EEPROM chip simply but using just PIO and DMA to improve the performance. I have no immediate use for this project myself but it piqued my interest to see what kind of improvement could be achieved.
> 
> _Is_ this faster? If it is, what kind of improvement was achieved? :slightly_smiling_face:

That's actually a _very_ good question and one I'm embarrassed to say I didn't actually directly check myself :slightly_frowning_face:.

The description of the original project states that he over-clocked the Pico to 400MHz and has it working stably with a system clock of 2MHz on his external board.  My understanding was that he'd found it necessary to over-clock the Pico so much in order to get that stability (why would you bother otherwise particularly when it means the flash can't keep up, so you're forced to solve an additional problem?).

My goal was to see whether that target could be achieved using PIO and DMA without having to over-clock (or at least, not as much).  I was also using it as an exercise for myself to get more experience using PIO and DMA, which is probably why I didn't bother to compare things.

Reading the original description again, he doesn't actually state that he _needed_ to over-clock.

I've tried using the original, non-PIO code in my main function without over-clocking.  So far it actually seems like it will just about cope with a new address every 90ns at system clock of 125MHz.  Looking at the generated code, the main loop consists of 9 instructions.  I believe all the instructions execute in one cycle bar the one fetching the data byte from RAM and the branch, which both need two.  Assuming no interrupts or stalling, that would be 11/125000000 == 88ns so that seems to be right.

Unless I've really messed something up with my measurements, there was absolutely no need to over-clock to 400MHz to handle his 6502 running with a 2MHz clock.  If each cycle takes 88ns and there's nothing to synchronise when the value on the address bus can change, you'd want the address to remain stable for more than 166ns to be sure of always getting the right data byte.  166ns would equate to 6MHz (which would be a bit knife-edge).  Even if the address changed every 200ns, that would still be 5MHz.

Now the PIO/DMA implementation.  There are only three instructions in the loop but the final `out` will stall until the data byte has been provided so I added a side-set to toggle another pin so we can see how long one cycle takes and how long the SM stalls for:
```
.wrap_target
    ; Shift the address bus into the ISR
    in pins, addr_bus_width side 0
    
    ; Shift in the top-most address bits of the array holding the EEPROM data
    ; This will cause auto-push to push the ISR to our RX FIFO
    in x, (32 - addr_bus_width)

    ; Auto-pull the data from the TX FIFO and put it on the data bus
    out pins, data_bus_width side 1
.wrap
```

I measured 104ns for one loop (so 13 cycles at 125MHz) with the pin high for 88ns (11 cycles).  With 1 cycle for the `out` instruction itself, that means 10 cycles for the two DMA operations and whatever else is involved there.  It's not clear to me at the moment what happens at each clock cycle during this period.  Does writing the address to the second DMA channel's `READ_ADD_TRIG` register cause it to start on the following cycle, or is there some latency between triggering a DMA channel and it actually starting?

So it seems the PIO/DMA method is actually a little slower than the C code implementation.  Obviously it has the advantage of running completely autonomously whereas you couldn't do anything else on the core running the C implementation.  For the intended scenario, that may not actually matter though.

> > The code as presented here just has an address and data bus of 4 bits to make testing easier but these are defined in eeprom.pio and can be easily changed and will not affect the efficiency.
> 
> Looking at the code in `main.c`, it seems that the address bus can't be bigger than 16 bits, and the data bus can't be bigger than 8 bits?

16 bits for the address bus is more a limitation of the array holding the addresses for the test program.  Unless I've missed something, the main PIO code will happily work with up to 32 bits (if that many pins were actually available).

The data bus can't currently be bigger than 8 bits, that's true.  Moving to a maximum of 16 bits shouldn't be too difficult though.  Mainly a case of changing the DMA configuration and the base type of the array holding the data.  At some point you're probably going to run out of pins!

> Might be worth adding the answers to both of these questions to `README.md` ?

Yes.  It needs a bit of attention :disappointed:

**Comment by lurch** [comment]
> I was also using it as an exercise for myself to get more experience using PIO and DMA

Yeah, that's what I figured - a laudable aim! :+1: 

> So it seems the PIO/DMA method is actually a little slower than the C code implementation.

Yeah, the only reason I asked is that the C implementation is so simple https://github.com/nickbild/picoROM/blob/main/rom.c#L35-L37 it's hard to imagine how any other approach would actually be faster. Would the C version be any faster if the `get_requested_address` and `put_data_on_bus` functions were declared as `inline`, or is that an optimisation that the compiler does anyway, given how small they are?

> Obviously it has the advantage of running completely autonomously whereas you couldn't do anything else on the core running the C implementation. For the intended scenario, that may not actually matter though.

Indeed. It occurred to me that you could probably run that tight loop on the second core though, and then run something _like_ your flashloader project on the first core, so that you could update the "ROM image" on the Pico whilst it's still running, without having to build and flash a new UF2 :wink: 

> 16 bits for the address bus is more a limitation of the array holding the addresses for the test program. Unless I've missed something, the main PIO code will happily work with up to 32 bits (if that many pins were actually available).

Ah yes, I hadn't noticed that the `DMA_SIZE_16` is only used inside your `initTest` https://github.com/rhulme/picoROM_pio/blob/master/main.c#L104 and the "main part" indeed uses `DMA_SIZE_32` https://github.com/rhulme/picoROM_pio/blob/master/main.c#L51

I wonder if running the "test" code on a separate Pico (instead of running both the "main" and "test" on the same Pico) might free up more bus / crossbar / DMA bandwidth for your "main" code? (apologies if that's a naive question) :shrug: 

> It's not clear to me at the moment what happens at each clock cycle during this period. Does writing the address to the second DMA channel's READ_ADD_TRIG register cause it to start on the following cycle, or is there some latency between triggering a DMA channel and it actually starting?

I've got no idea myself, but feel free to ask at https://github.com/raspberrypi/pico-feedback :slightly_smiling_face:

**Comment by rhulme** [comment]
> > So it seems the PIO/DMA method is actually a little slower than the C code implementation.
> 
> Yeah, the only reason I asked is that the C implementation is so simple https://github.com/nickbild/picoROM/blob/main/rom.c#L35-L37 it's hard to imagine how any other approach would actually be faster. Would the C version be any faster if the `get_requested_address` and `put_data_on_bus` functions were declared as `inline`, or is that an optimisation that the compiler does anyway, given how small they are?

Yes, they get inlined by the compiler.  It might be possible to shave another cycle off what's generated but I think it's pretty much at the limit.

I have no clue now why the original project overclocked the Pico so much (or at all).

> > Obviously it has the advantage of running completely autonomously whereas you couldn't do anything else on the core running the C implementation. For the intended scenario, that may not actually matter though.
> 
> Indeed. It occurred to me that you could probably run that tight loop on the second core though, and then run something _like_ your flashloader project on the first core, so that you could update the "ROM image" on the Pico whilst it's still running, without having to build and flash a new UF2 😉

Yes, I had the same thought!  Using the second core would certainly allow you do something else at the same time.

> I wonder if running the "test" code on a separate Pico (instead of running both the "main" and "test" on the same Pico) might free up more bus / crossbar / DMA bandwidth for your "main" code? (apologies if that's a naive question) 🤷

It's possible but I don't _think_ so.  I didn't notice any jitter in the timing pulses for the main code.  If the two routines are not completely in sync (and they're not) but were causing some kind resource conflict, I'd expect to see a bit of jitter.

I just need to get myself a second Pico now to check :smirk:

> > It's not clear to me at the moment what happens at each clock cycle during this period. Does writing the address to the second DMA channel's READ_ADD_TRIG register cause it to start on the following cycle, or is there some latency between triggering a DMA channel and it actually starting?
> 
> I've got no idea myself, but feel free to ask at https://github.com/raspberrypi/pico-feedback 🙂

I will do that 🙂

**Comment by lurch** [comment]
I don't think there's much more to be said, so I'll close this issue now. Thanks for your answers! :+1:
